### ISSUE TITLE
System.Type does not contain GenericTypeArguments

### ISSUE THREAD

**Issue by SJLynch94** [SirPolly/UtilityAI#1]
Hi SirPolly, 

I have tried to import your Utility AI with Unity. All files are in place but there seems to be 2 errors which are within: **Editor/InputScorerNode.cs** and **Editor/ActionWithInputsNode.cs**. I have checked into the error and System.Type or Type do not have a definition for GenericTypeArguments which are on **line 15 in InputScorerNode.cs** and **line 17 ActionWithInputsNode.cs**. I am currently working within Unity 2018.2.17f1, and I believe that version of Unity uses C# version 4.0. I hope this helps if there is an issue within your Utility AI or whether it is just my version of Unity or C# that is causing the problems.

Thanks

**Comment by OneManMonkeySquad** [comment]
Should be fixed now. The editor didn't properly ignore abstract classes.

**Comment by SJLynch94** [comment]
After you have done your last commit to fix that issue it has now changed to a different issue: **Assets/UtilityAI/Editor/InputScorerNode.cs(14,65): error CS1061: Type `System.Type' does not contain a definition for `GenericTypeArguments' and no extension method `GenericTypeArguments' of type `System.Type' could be found. Are you missing an assembly reference?**, along with **Assets/UtilityAI/Editor/ActionWithInputsNode.cs(16,65): error CS1061: Type `System.Type' does not contain a definition for `GenericTypeArguments' and no extension method `GenericTypeArguments' of type `System.Type' could be found. Are you missing an assembly reference?**. Unity and C# are still the same version, could I be missing something like distributions needed for the editor side to work? Thanks for the updates

**Comment by OneManMonkeySquad** [comment]
No, the library has no dependencies. I'll look into it over the weekend.

**Comment by OneManMonkeySquad** [comment]
Fixed :)
