### ISSUE TITLE
Usability question?

### ISSUE THREAD

**Issue by MihailTrajkovski** [SirPolly/UtilityAI#3]
Hey,

I had discovered your project a couple months prior and I planned on using it (or parts of it) in my project but now that I got to the stage where i must implement the AI i see that you marked is a non production... I do plan on using it for a game thats going to be released in a couple of months so could you tell what are the major reasons why this shouldn't be used in production?

Also how hard would it be to change the AI evaluation phase from a real-time one( idk if your system evaluation phase is real time i am just guessing sorry if it isn't true) to a one useful for a turn based game where the AI will do evaluations each turn?

Thank you and wish you good luck!

**Comment by OneManMonkeySquad** [comment]
Ahoy,

that's nice :) I would love to get a notice when your game is done. Good luck! You are of course free to do whatever you like with it. With non-production ready I meant I'm not actively providing more features. In an actual game you might miss advanced features of other utility ai implementations (Apex comes to mind).

To use the ai in a turn based game just call AI.Process once per enemy turn. In the actions queue commands, animations, ... . When this queue is empty the enemy turn is done. Should be possible.

Cheers
