### ISSUE TITLE
Could you provide more docs please,I do not know how to use.

### ISSUE THREAD

**Issue by GITHUB243884919** [SirPolly/UtilityAI#6]
As you said,  I copied it into my Unity project, And I add a new file TestAgent.cs that almost same as your "Getting Started" class TestContext ....  but I won't see any thing in UtilityAI Editor. What should I do? Thank you.
![2020116-115250](https://user-images.githubusercontent.com/17681628/72492456-425ead80-3858-11ea-87ed-43c5c88faaf5.jpg)
![2020116-115400](https://user-images.githubusercontent.com/17681628/72492462-44c10780-3858-11ea-8f49-8b514b8b8ec9.jpg)

**Comment by OneManMonkeySquad** [comment]
Hello,

I'm sorry the example is not correct. You need to put all actions, (context) scorers, ... in their own files (per class) because they are **ScriptableObjects**. This is required by Unity.

I'll update the docs.
